windowrule {
  name = windowrule-1
  float = on
  size = 622 625
  stay_focused = on
  match:class = (clipse)
}


# Window rule of filelight

windowrule {
  name = windowrule-2
  float = on
  size = 800 600
  match:class = ^(imv)$
}


windowrule {
  name = windowrule-3
  float = on
  size = 600 400
  match:class = ^(yad-icon-browser)$
}


windowrule {
  name = windowrule-4
  float = on
  center = on
  size = 800 600
  match:class = ^(VirtualBox Manager)$
}

windowrule {
  name = windowrule-5
  float = on
  center = on
  size = 700 600
  opacity = 0.75 0.75
  match:class = ^(thunar)$
}


windowrule {
  name = windowrule-6
  opacity = 0.8 override
  match:class = ^(kitty)$
}

windowrule {
  name = windowrule-7
  opacity = 0.70 0.70
  float = on
  center = on
  size = 600 400
  match:class = ^(Alacritty)$
}

windowrule {
  name = windowrule-8
  opacity = 0.28 0.28
  match:class = ^(wlogout)$
}


windowrule {
  name = windowrule-9
  center = on
  float = on
  size = 800 600
  match:class = ^(Bitwarden)$
}


windowrule {
  name = windowrule-10
  float = on
  center = on
  size = 800 600
  match:class = ^(org.kde.filelight)$
}


windowrule {
  name = windowrule-11
  float = on
  center = on
  size = 800 600
  match:class = ^(org.pulseaudio.pavucontrol)$
}


windowrule {
  name = windowrule-12
  float = on
  center = on
  size = 800 600
  match:class = ^(org.kde.dolphin)$
}


windowrule {
  name = windowrule-13
  float = on
  center = on
  size = 700 500
  match:class = ^(org.gnome.Shotwell)$
}


windowrule {
  name = windowrule-14
  float = on
  size = 800 400
  center = on
  match:class = ^(waypaper)$
}


windowrule {
  name = windowrule-15
  opacity = 0.80 0.80
  match:class = ^(wlogout)$s
}


windowrule {
  name = windowrule-16
  float = on
  size = 700 500
  center = on
  match:class = ^(org.kde.kwrite)$
}


windowrule {
  name = windowrule-17
  float = on
  size = 900  670
  center = on
  match:class = ^(discord)$
}



windowrule {
  name = windowrule-18
  float = on
  size = 800 600
  center = on
  match:class = ^(nwg-look)$
}


windowrule {
  name = windowrule-19
  float = on
  center = on
  size = 900  670
  match:class = ^(spotify)$
}


windowrule {
  name = windowrule-20
  float = on
  center = on
  size = 600 400
  match:class = ^(feh)$
}



windowrule {
  name = windowrule-21
  float = on
  center = on
  size = 800 600
  match:class = ^(blueman-manager)$
}


windowrule {
  name = windowrule-22
  float = on
  center = on
  size = 700 500
  match:class = ^(org.kde.kate)$
}


windowrule {
  name = windowrule-23
  center = on
  float = on
  size = 700 500
  match:class = ^(vlc)$
}


windowrule {
  name = windowrule-24
  opacity = 0.80 0.80
  match:class = ^(rofi)$
}

windowrule {
  name = windowrule-25
  opacity = 0.69 0.78
  match:class = ^(waybar)$
}

windowrule {
  name = windowrule-26
  float = on
  center = on
  size = 450 670
  opacity = 0.75 0.75
  match:class = ^(com.example.moonvyrox)$
}

layerrule {
  name = layerrule-1
  blur = on
  ignore_alpha = 0
  match:namespace = rofi
}



layerrule {
  name = layerrule-2
  blur = on
  match:namespace = swayosd
}

layerrule {
  name = layerrule-3
  blur = on
  ignore_alpha = 0
  match:namespace = kitty
}

layerrule {
  name = layerrule-4
  blur = on
  match:namespace = Alacritty
}

layerrule {
  name = layerrule-5
  blur = on
  ignore_alpha = 0.1
  match:namespace = waybar
}

layerrule {
  name = layerrule-6
  no_anim = on
  match:namespace = hyprpicker
}

layerrule {
  name = layerrule-8
  blur = on
  match:namespace = logout_dialog
}

layerrule {
  name = layerrule-8
  ignore_alpha = 0
  match:namespace = logout_dialog
}


layerrule {
  name = layerrule-7
  no_anim = on
  match:namespace = selection
}
